# Generated by Django 2.2 on 2021-02-18 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('number_doc', models.CharField(max_length=10)),
                ('user_doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patient_id', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('emergency_number', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('health_condition', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('alternate_email', models.CharField(max_length=100)),
                ('doctorw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help', to='covid.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patientsymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btemp', models.IntegerField()),
                ('sympt1', models.CharField(max_length=100)),
                ('patient_fkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalpatientsymptoms',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('btemp', models.IntegerField()),
                ('sympt1', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient_fkey', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='covid.patient')),
            ],
            options={
                'verbose_name': 'historical patientsymptoms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
